### ISSUE TITLE
adjust configuration file considering what mode is being runned

### ISSUE THREAD

**Issue by d-roak** [topology-foundation/infra#3]
it can be runned in `bootstrap` or `node` modes, the configs are different for both

https://github.com/topology-foundation/infra/blob/d2075cb7cc70fb941e238361d3b9e95ad293b7e8/ansible/roles/topology-node/tasks/main.yaml

**Comment by winprn** [comment]
the run mode should be determined by environment variable or pass as a flag?

**Comment by d-roak** [comment]
here:
https://github.com/topology-foundation/infra/blob/d2075cb7cc70fb941e238361d3b9e95ad293b7e8/ansible/playbooks/setup_hosts.yaml#L5
